# Copyright (c) 2017-2023, Niklas Hauser
#
# This file is part of the modm project.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

#!/usr/bin/env python3

from os.path import join, abspath
Import("env")

profile = ARGUMENTS.get("profile", "release")
# Toolchain configuration








env.AppendUnique(CPPPATH=[
    abspath("src"),
])

files = [
    env.File("src/micro-motor/logger.cpp"),
]
library = env.StaticLibrary(target="micro-motor", source=files)

env.AppendUnique(LIBS=[
    library,
])
env.AppendUnique(LIBPATH=[
    abspath(str(library[0].get_dir())),
])
Return("library")
