# MIT License

# Copyright (c) 2024 Henrik Hose

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from casadi import sin, cos, vertcat
def fb(phi, theta, dpsi, dphi, dtheta, dq_W, dq_R, m_W, m_B, m_R, I_Wx, I_Wy, I_Wz, I_Bx, I_By, I_Bz, I_Rx, I_Ry, I_Rz, r_W, l_WB):
    return vertcat(
        I_Wy*dphi*dq_W*cos(phi)-I_Wx*dphi*dq_W*cos(phi)+I_Wz*dphi*dq_W*cos(phi)+I_Bx*dphi*dtheta*cos(phi)+I_By*dphi*dtheta*cos(phi)-I_Bz*dphi*dtheta*cos(phi)+I_Rx*dphi*dtheta*cos(phi)+I_Ry*dphi*dtheta*cos(phi)-I_Rz*dphi*dtheta*cos(phi)-I_Bx*dphi*dpsi*sin(2*phi)+I_By*dphi*dpsi*sin(2*phi)-I_Rx*dphi*dpsi*sin(2*phi)+I_Ry*dphi*dpsi*sin(2*phi)+I_Wy*dphi*dpsi*sin(2*phi)-I_Wz*dphi*dpsi*sin(2*phi)+I_Bx*dphi**2*cos(theta)*sin(phi)*sin(theta)-I_Bz*dphi**2*cos(theta)*sin(phi)*sin(theta)+I_Rx*dphi**2*cos(theta)*sin(phi)*sin(theta)-I_Rz*dphi**2*cos(theta)*sin(phi)*sin(theta)-I_Rx*dq_R*dtheta*cos(phi)*cos(theta)+I_Ry*dq_R*dtheta*cos(phi)*cos(theta)-I_Rz*dq_R*dtheta*cos(phi)*cos(theta)+2*dphi*dtheta*l_WB**2*m_B*cos(phi)+8*dphi*dtheta*l_WB**2*m_R*cos(phi)+I_Rx*dphi*dq_R*sin(phi)*sin(theta)+I_Ry*dphi*dq_R*sin(phi)*sin(theta)-I_Rz*dphi*dq_R*sin(phi)*sin(theta)-2*I_Bx*dphi*dtheta*cos(phi)*cos(theta)**2+2*I_Bz*dphi*dtheta*cos(phi)*cos(theta)**2-2*I_Rx*dphi*dtheta*cos(phi)*cos(theta)**2+2*I_Rz*dphi*dtheta*cos(phi)*cos(theta)**2+dphi*dpsi*m_B*r_W**2*sin(2*phi)+dphi*dpsi*m_R*r_W**2*sin(2*phi)+dphi*dpsi*m_W*r_W**2*sin(2*phi)+2*I_Ry*dpsi*dq_R*cos(phi)*cos(theta)*sin(phi)-2*I_Rz*dpsi*dq_R*cos(phi)*cos(theta)*sin(phi)+dphi**2*l_WB*m_B*r_W*sin(phi)*sin(theta)+2*dphi**2*l_WB*m_R*r_W*sin(phi)*sin(theta)-dtheta**2*l_WB*m_B*r_W*sin(phi)*sin(theta)-2*dtheta**2*l_WB*m_R*r_W*sin(phi)*sin(theta)+dpsi*dq_W*l_WB*m_B*r_W*sin(theta)+2*dpsi*dq_W*l_WB*m_R*r_W*sin(theta)-2*dpsi*dtheta*l_WB*m_B*r_W*sin(theta)-4*dpsi*dtheta*l_WB*m_R*r_W*sin(theta)+2*I_Bx*dphi*dpsi*cos(phi)*cos(theta)**2*sin(phi)-2*I_Bz*dphi*dpsi*cos(phi)*cos(theta)**2*sin(phi)+2*I_Rx*dphi*dpsi*cos(phi)*cos(theta)**2*sin(phi)-2*I_Rz*dphi*dpsi*cos(phi)*cos(theta)**2*sin(phi)+2*I_Bx*dpsi*dtheta*cos(phi)**2*cos(theta)*sin(theta)-2*I_Bz*dpsi*dtheta*cos(phi)**2*cos(theta)*sin(theta)+2*I_Rx*dpsi*dtheta*cos(phi)**2*cos(theta)*sin(theta)-2*I_Rz*dpsi*dtheta*cos(phi)**2*cos(theta)*sin(theta)-2*dphi*dtheta*l_WB**2*m_B*cos(phi)*cos(theta)**2-8*dphi*dtheta*l_WB**2*m_R*cos(phi)*cos(theta)**2+dphi**2*l_WB**2*m_B*cos(theta)*sin(phi)*sin(theta)+4*dphi**2*l_WB**2*m_R*cos(theta)*sin(phi)*sin(theta)+2*dphi*dpsi*l_WB**2*m_B*cos(phi)*cos(theta)**2*sin(phi)+8*dphi*dpsi*l_WB**2*m_R*cos(phi)*cos(theta)**2*sin(phi)+2*dpsi*dtheta*l_WB**2*m_B*cos(phi)**2*cos(theta)*sin(theta)+8*dpsi*dtheta*l_WB**2*m_R*cos(phi)**2*cos(theta)*sin(theta)+2*dpsi*dtheta*l_WB*m_B*r_W*cos(phi)**2*sin(theta)+4*dpsi*dtheta*l_WB*m_R*r_W*cos(phi)**2*sin(theta)+4*dphi*dpsi*l_WB*m_B*r_W*cos(phi)*cos(theta)*sin(phi)+8*dphi*dpsi*l_WB*m_R*r_W*cos(phi)*cos(theta)*sin(phi),
        (I_Bx*dpsi**2*sin(2*phi))/2-(I_By*dpsi**2*sin(2*phi))/2+(I_Rx*dpsi**2*sin(2*phi))/2-(I_Ry*dpsi**2*sin(2*phi))/2-(I_Wy*dpsi**2*sin(2*phi))/2+(I_Wz*dpsi**2*sin(2*phi))/2-I_Wx*dpsi*dq_W*cos(phi)-I_Wy*dpsi*dq_W*cos(phi)+I_Wz*dpsi*dq_W*cos(phi)+I_Bx*dpsi*dtheta*cos(phi)-I_By*dpsi*dtheta*cos(phi)-I_Bz*dpsi*dtheta*cos(phi)+I_Rx*dpsi*dtheta*cos(phi)-I_Ry*dpsi*dtheta*cos(phi)-I_Rz*dpsi*dtheta*cos(phi)-I_Rx*dq_R*dtheta*sin(theta)+I_Ry*dq_R*dtheta*sin(theta)-I_Rz*dq_R*dtheta*sin(theta)-(dpsi**2*m_B*r_W**2*sin(2*phi))/2-(dpsi**2*m_R*r_W**2*sin(2*phi))/2-(dpsi**2*m_W*r_W**2*sin(2*phi))/2-I_Bx*dphi*dtheta*sin(2*theta)+I_Bz*dphi*dtheta*sin(2*theta)-I_Rx*dphi*dtheta*sin(2*theta)+I_Rz*dphi*dtheta*sin(2*theta)-dpsi*dq_W*m_B*r_W**2*cos(phi)-dpsi*dq_W*m_R*r_W**2*cos(phi)-dpsi*dq_W*m_W*r_W**2*cos(phi)-I_Rx*dpsi*dq_R*sin(phi)*sin(theta)+I_Ry*dpsi*dq_R*sin(phi)*sin(theta)-I_Rz*dpsi*dq_R*sin(phi)*sin(theta)-I_Bx*dpsi**2*cos(phi)*cos(theta)**2*sin(phi)+I_Bz*dpsi**2*cos(phi)*cos(theta)**2*sin(phi)-I_Rx*dpsi**2*cos(phi)*cos(theta)**2*sin(phi)+I_Rz*dpsi**2*cos(phi)*cos(theta)**2*sin(phi)-2*I_Bx*dpsi*dtheta*cos(phi)*cos(theta)**2+2*I_Bz*dpsi*dtheta*cos(phi)*cos(theta)**2-2*I_Rx*dpsi*dtheta*cos(phi)*cos(theta)**2+2*I_Rz*dpsi*dtheta*cos(phi)*cos(theta)**2-dphi*dtheta*l_WB**2*m_B*sin(2*theta)-4*dphi*dtheta*l_WB**2*m_R*sin(2*theta)-dpsi**2*l_WB**2*m_B*cos(phi)*cos(theta)**2*sin(phi)-4*dpsi**2*l_WB**2*m_R*cos(phi)*cos(theta)**2*sin(phi)-2*dphi*dtheta*l_WB*m_B*r_W*sin(theta)-4*dphi*dtheta*l_WB*m_R*r_W*sin(theta)-2*dpsi*dtheta*l_WB**2*m_B*cos(phi)*cos(theta)**2-8*dpsi*dtheta*l_WB**2*m_R*cos(phi)*cos(theta)**2-dpsi*dq_W*l_WB*m_B*r_W*cos(phi)*cos(theta)-2*dpsi*dq_W*l_WB*m_R*r_W*cos(phi)*cos(theta)-2*dpsi*dtheta*l_WB*m_B*r_W*cos(phi)*cos(theta)-4*dpsi*dtheta*l_WB*m_R*r_W*cos(phi)*cos(theta)-2*dpsi**2*l_WB*m_B*r_W*cos(phi)*cos(theta)*sin(phi)-4*dpsi**2*l_WB*m_R*r_W*cos(phi)*cos(theta)*sin(phi),
        (I_Bx*dphi**2*sin(2*theta))/2-(I_Bz*dphi**2*sin(2*theta))/2+(I_Rx*dphi**2*sin(2*theta))/2-(I_Rz*dphi**2*sin(2*theta))/2-I_Bx*dphi*dpsi*cos(phi)+I_By*dphi*dpsi*cos(phi)+I_Bz*dphi*dpsi*cos(phi)-I_Rx*dphi*dpsi*cos(phi)+I_Ry*dphi*dpsi*cos(phi)+I_Rz*dphi*dpsi*cos(phi)+I_Rx*dphi*dq_R*sin(theta)+I_Ry*dphi*dq_R*sin(theta)-I_Rz*dphi*dq_R*sin(theta)+(dphi**2*l_WB**2*m_B*sin(2*theta))/2+2*dphi**2*l_WB**2*m_R*sin(2*theta)+I_Rx*dpsi*dq_R*cos(phi)*cos(theta)+I_Ry*dpsi*dq_R*cos(phi)*cos(theta)-I_Rz*dpsi*dq_R*cos(phi)*cos(theta)+dphi**2*l_WB*m_B*r_W*sin(theta)+dpsi**2*l_WB*m_B*r_W*sin(theta)+2*dphi**2*l_WB*m_R*r_W*sin(theta)+2*dpsi**2*l_WB*m_R*r_W*sin(theta)-I_Bx*dpsi**2*cos(phi)**2*cos(theta)*sin(theta)+I_Bz*dpsi**2*cos(phi)**2*cos(theta)*sin(theta)-I_Rx*dpsi**2*cos(phi)**2*cos(theta)*sin(theta)+I_Rz*dpsi**2*cos(phi)**2*cos(theta)*sin(theta)+2*I_Bx*dphi*dpsi*cos(phi)*cos(theta)**2-2*I_Bz*dphi*dpsi*cos(phi)*cos(theta)**2+2*I_Rx*dphi*dpsi*cos(phi)*cos(theta)**2-2*I_Rz*dphi*dpsi*cos(phi)*cos(theta)**2-dpsi**2*l_WB**2*m_B*cos(phi)**2*cos(theta)*sin(theta)-4*dpsi**2*l_WB**2*m_R*cos(phi)**2*cos(theta)*sin(theta)+2*dphi*dpsi*l_WB**2*m_B*cos(phi)*cos(theta)**2+8*dphi*dpsi*l_WB**2*m_R*cos(phi)*cos(theta)**2-dpsi**2*l_WB*m_B*r_W*cos(phi)**2*sin(theta)-2*dpsi**2*l_WB*m_R*r_W*cos(phi)**2*sin(theta)+2*dphi*dpsi*l_WB*m_B*r_W*cos(phi)*cos(theta)+4*dphi*dpsi*l_WB*m_R*r_W*cos(phi)*cos(theta)+dpsi*dq_W*l_WB*m_B*r_W*sin(phi)*sin(theta)+2*dpsi*dq_W*l_WB*m_R*r_W*sin(phi)*sin(theta),
        I_Wx*dphi*dpsi*cos(phi)+I_Wy*dphi*dpsi*cos(phi)-I_Wz*dphi*dpsi*cos(phi)+2*dphi*dpsi*m_B*r_W**2*cos(phi)+2*dphi*dpsi*m_R*r_W**2*cos(phi)+2*dphi*dpsi*m_W*r_W**2*cos(phi)-dpsi**2*l_WB*m_B*r_W*sin(theta)-2*dpsi**2*l_WB*m_R*r_W*sin(theta)-dtheta**2*l_WB*m_B*r_W*sin(theta)-2*dtheta**2*l_WB*m_R*r_W*sin(theta)+2*dphi*dpsi*l_WB*m_B*r_W*cos(phi)*cos(theta)+4*dphi*dpsi*l_WB*m_R*r_W*cos(phi)*cos(theta)-2*dpsi*dtheta*l_WB*m_B*r_W*sin(phi)*sin(theta)-4*dpsi*dtheta*l_WB*m_R*r_W*sin(phi)*sin(theta),
        I_Rz*dphi*dtheta*sin(theta)-I_Ry*dphi*dtheta*sin(theta)-I_Rx*dphi*dtheta*sin(theta)-(I_Ry*dpsi**2*sin(2*phi)*cos(theta))/2+(I_Rz*dpsi**2*sin(2*phi)*cos(theta))/2-I_Rx*dpsi*dtheta*cos(phi)*cos(theta)-I_Ry*dpsi*dtheta*cos(phi)*cos(theta)+I_Rz*dpsi*dtheta*cos(phi)*cos(theta)+I_Rx*dphi*dpsi*sin(phi)*sin(theta)-I_Ry*dphi*dpsi*sin(phi)*sin(theta)+I_Rz*dphi*dpsi*sin(phi)*sin(theta)
    )
